---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: gcc:latest
  commands:
  - gcc -lpthread ./pthread.c -o ./pthread
  - gcc ./lambda.c -o ./lambda
- name: test
  image: gcc:latest
  commands:
  - ./lambda

